### ISSUE TITLE
Upload list in version 3.3 does not work - throws JS error

### ISSUE THREAD

**Issue by angelicalleite** [AtlasOfLivingAustralia/specieslist-webapp#114]
I installed version 3.3 and not upload list and not check data, I can also download the list and ALA Plataform perform this task and not success.

**Comment by nickdos** [comment]
Looks like the latest version has slightly newer version of jQuery that is throwing a JS error, where it previously ignored it.

The bug is in the `ajax` call inside the `parseColumns()` function, on this line:

```
    contentType: !isFileUpload,
```

contentType is expected to be a String but in this case is sending a Boolean, which causes jQuery to fail with error `Uncaught TypeError: (v.contentType || "").indexOf is not a function`.

Fix is to convert to a string (empty string for false and some_value for true).

**Comment by nickdos** [comment]
Fixed in version 3.4

**Comment by ansell** [comment]
I did code review and functional testing for this
