### ISSUE TITLE
Default all new lists to isPrivate=true

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/specieslist-webapp#120]
To reduce the amount of clutter in the public view of lists, all new lists submitted via the spatial portal and other tools should default to isPrivate=true. This wont effect a users own visibility of their lists and only affect the visibility https://lists.ala.org.au list search.

[20-04-2021]
- [ ] Update private list checkbox, make it ticked by default.

**Comment by djtfmartin** [comment]
Related to #118

**Comment by nickdos** [comment]
Just tried a test and got an error. Same data on production worked. 

![image](https://user-images.githubusercontent.com/532845/78726842-62dd6600-7976-11ea-8a1f-130d930a3e3d.png)

**Comment by nickdos** [comment]
Looking at the [successful list](https://lists-test.ala.org.au/speciesListItem/list/dr14046) I created, it appears to have `isPrivate=false`:

![image](https://user-images.githubusercontent.com/532845/78729547-a6879e00-797d-11ea-9a41-ff04fd5d0450.png)

**Comment by Tasilee** [comment]
Sorry but I disagree with the philosophy here. The issue is more that we have too many lists that are temporary and are not being removed and we don't have an adequate mechanism for filtering lists. A private list is not findable by other users and the whole idea is sharing of information.

I added issues #136, #137, #138 and #139 based on what I wrote in my October 2019 report to Andre:

- I raised many of the List issue with an email to Natasha, John, Peter and Dave 20/12/2013! We need some action.
- Type "Local checklist" should be named "Area checklist"
- "Area checklist’s” requires mandatory definition of area (WKT or select from gazetteer).
- Authoritative lists must be either maintained by the authority or ideally the source lists should be tapped by web services daily, monthly. 
- As previously discussed, there are HEAPS of 'area checklists' out there that we need a campaign to capture. This is particularly true of islands and small reserves. 
- We need to find out what list Type "Other" contains and add more categories so this category can be reduced
- We need definitions of List Types in our vocabulary system with links from where used. E.g., what are "Profile lists"?
- We need an automatic notification to users of Lists with link to either 'Renew' or 'Remove' after say 12 months.
- List type "Sensitive list of species" should be called "List of sensitive species"! (it isn't a sensitive list)
- List type "Spatial portal defined list" should be replaced by request to user at the time for List TYPE (which shouldn't be "Spatial Portal defined list". Issue SH#263 added.
- List type "Test list" should be "Temporary" and be deleted after one month with user pre-notification "set to non-temp category or it will be deleted"
- Wishlist: A vocabulary is needed to check all uploaded column names. Ideally, the vocab system should specify the nature of the values that name supports. We know in many cases, a vocab or values (or even if it is a continuous value such as temperature) doesn’t exist, hence TDWG Data Quality Task Group 4. New column header terms (not in vocabulary) should be manually queried, closest matches displayed and if necessary, definitions and values types added with user name.
- Uploaded authoritative lists that are used elsewhere in the ALA need to be validated, probably manually.
- Name matching: What happens when (taxon) name mismatches occur? Currently nothing, as they are left as is. Ideally, mismatches should report a match score as one of the current web services reports. The user can then decide what action needs to be taken. Should we also tap GBIF’s name service – yes, as it would provide a useful context.
- What happens when there is an update to NSLs? If there is an update, should we scan mismatches in Lists and notify the user of potential new matches? This would be particularly important for ‘authoritative’ lists.
- We are getting a number of user-entered lists that are in theory authoritative, but in reality, aren’t because the author is not representing the ‘authority’. For example: https://lists.ala.org.au/speciesListItem/list/dr13730. 
-

**Comment by nickdos** [comment]
I'd be OK with leaving as default as `public` and implementing better filtering and some human action to monitor lists as a way of achieving the desired outcome of clearing out old clutter (issue is being worked on for adding facets so we can filter for these). It all comes down to whether ALA users are actually using lists from other users and I'm not sure we know one way or the other. @djtfmartin comments?

**Comment by Rita-C** [comment]
@nickdos , @Tasilee , Based on Lee's comment, I'm going to revert the change of this ticket, i.e. leave default to be public.
ref comment Type "Local checklist" should be named "Area checklist", should #137 (List type "Local checklist" should be renamed "Species checklist") be updated @Tasilee ?

**Comment by Tasilee** [comment]
Thanks @Rita-C . Yes, we need to change the name "Local checklist" to "Species checklist" to align with ecological accepted (best) practice. In association with this, we really do need to action #138

**Comment by Rita-C** [comment]
default private list code changes reverted.

**Comment by djtfmartin** [comment]
Apologies @nickdos for only commenting late on, but my preference would be to default `isPrivate=true`.

I appreciate @Tasilee's comments on getting folks to collaborate on lists, that would be great to see. But the problem we have is that i think the  default `isPrivate=false` is giving people a bad impression of the general data in the tool, and will probably put collaborators off treating it with any real purpose. It's a hard sell to get people to take it seriously when all they see is lists with the names "Test123" etc.

If you look at recent uploads, most if not all where probably intended to be private lists by the user:

<img width="1631" alt="Screen Shot 2020-04-16 at 11 43 04 am" src="https://user-images.githubusercontent.com/444897/79447723-2fcf4e00-7fd8-11ea-867b-448faf072093.png">

So my suggestion is to default to `isPrivate=false` but make it clearer in the UI what this means by changing the following:

<img width="1231" alt="Screen Shot 2020-04-16 at 11 49 20 am" src="https://user-images.githubusercontent.com/444897/79447825-5d1bfc00-7fd8-11ea-80f0-8c3ff1e403b0.png">

to include a checkbox list:

[ ] do you want share this list with other users ?

and do something similar in the spatial portal. Instead of "Make Private" add something more descriptive.

<img width="906" alt="Screen Shot 2020-04-16 at 11 55 09 am" src="https://user-images.githubusercontent.com/444897/79448325-24305700-7fd9-11ea-8f1d-f26f4419dbc4.png">

**Comment by Tasilee** [comment]
Thanks @djtfmartin. I just talked with Adam yesterday about that default ticked 'private' in the SP and asked that it be changed to unticked. But happy to include a note about sharing as mentioned. This was part of the issue https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/263 (which I tested yesterday on spatial-test). 

I agree with anything that would elevate the benefits of list awareness and re-use. Part of our current problem is that we have way too many lists that were intended as temporary. I know of over 400 lists that were being used by one person for a series of EIAs that will be of no use one the report is finalized. We also have a heap of lists that are anonymous. This an other reasons are why I have added #139 - so that we can better review what is there and take some action to remove lists that are beyond their 'use by date'. I'd also be keen to see better education of how lists can be used, so I'd be happy to write something. Maybe (also), a case study.

I will be discussing the Lists issues with Andre and Hamish this morning in conjunction with my report on SP, ALA4R, and layers.

**Comment by Rita-C** [comment]
Code updated to show "is private" check box on UI for user to elect if the uploaded list is private.

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/specieslist-webapp/review/SW-CR-3

**Comment by nickdos** [comment]
Code needs to show `is private` to be ticked by default.

**Comment by nickdos** [comment]
Checked on test site - all looks good ✅
